'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { ProtectedLayout } from '../../../components/protected-layout';
import { cancelSale, getSaleById, SaleDetails } from '../../../lib/api';

const date = (value: string) => new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export default function SaleDetailsPage() {
  const params = useParams<{ id: string }>(); const [sale, setSale] = useState<SaleDetails | null>(null); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setSale(await getSaleById(params.id)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Не удалось загрузить продажу'); } finally { setLoading(false); } }, [params.id]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function cancel() { if (!sale || !reason.trim()) { setError('Укажите причину отмены'); return; } if (!window.confirm(`Отменить продажу ${sale.number}? Остатки будут восстановлены.`)) return; setBusy(true); setError(''); try { await cancelSale(sale.id, reason.trim()); setNotice('Продажа отменена. Остатки восстановлены.'); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Не удалось отменить продажу'); } finally { setBusy(false); } }
  return <ProtectedLayout><Link href="/sales" className="text-sm text-blue-700">← Все продажи</Link>{loading ? <p className="mt-5 text-slate-500">Загрузка…</p> : error && !sale ? <p className="mt-5 rounded bg-red-50 p-3 text-red-700">{error}</p> : sale && <><div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{sale.number}</h1><p className="text-slate-500">{date(sale.createdAt)} · {sale.shop.name}</p></div><span className={sale.status === 'COMPLETED' ? 'rounded bg-emerald-50 px-3 py-1 text-emerald-700' : 'rounded bg-slate-100 px-3 py-1 text-slate-600'}>{sale.status === 'COMPLETED' ? 'Проведена' : 'Отменена'}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="Итог" value={`${sale.totalAmount} ${sale.currency}`}/><Info label="Клиент" value={sale.customerName ?? 'Не указан'}/><Info label="Телефон" value={sale.customerPhone ?? 'Не указан'}/></div>{sale.notes && <p className="mt-4 rounded bg-white p-3 text-slate-600">{sale.notes}</p>}<div className="mt-5 overflow-x-auto rounded-xl bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Товар</th><th>Код / OEM</th><th>Количество</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>{sale.items.map((item) => <tr key={item.id} className="border-b"><td className="p-3"><b>{item.itemName}</b><br/><span className="text-slate-500">{item.partCatalogItem.category.name}</span></td><td>{item.partCatalogItem.internalCode}<br/>{item.oemNumber ?? item.inventoryItem.oemNumber ?? '—'}</td><td>{item.quantity}</td><td>{item.unitPrice} {sale.currency}</td><td>{item.lineTotal} {sale.currency}</td></tr>)}</tbody></table></div>{sale.status === 'COMPLETED' && <section className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-semibold">Отмена продажи</h2><p className="mt-1 text-sm text-slate-600">После отмены остатки будут восстановлены автоматически.</p><input value={reason} onChange={(event) => setReason(event.target.value)} className="mt-3 w-full rounded border p-2" placeholder="Причина отмены"/><button disabled={busy} onClick={() => void cancel()} className="mt-3 rounded bg-red-600 px-4 py-2 text-white disabled:bg-slate-300">{busy ? 'Отмена…' : 'Отменить продажу'}</button></section>}{notice && <p className="mt-4 rounded bg-emerald-50 p-3 text-emerald-700">{notice}</p>}{error && sale && <p className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{sale.status === 'CANCELLED' && <p className="mt-4 rounded bg-slate-100 p-3 text-slate-600">Причина отмены: {sale.cancelReason ?? 'не указана'}</p>}</>}</ProtectedLayout>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded bg-white p-3"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
