'use client';
import { Autocomplete,Box,TextField,Typography } from '@mui/material';
import SearchRounded from '@mui/icons-material/SearchRounded';
import { useEffect,useRef,useState } from 'react';
import { VehicleQuickSearchResult,vehicleCatalogQuickSearch } from '../lib/api';
type Props={initialValue?:string;onSelect:(value:VehicleQuickSearchResult)=>void;disabled?:boolean;autoFocus?:boolean};
const details=(o:VehicleQuickSearchResult)=>[o.matchedAlias,o.generationName,o.yearFrom?`${o.yearFrom}–${o.yearTo??'н.в.'}`:null,o.powertrain].filter(Boolean).join(' · ')||'Спецификация пока не выбрана';
export function VehicleQuickSearch({initialValue='',onSelect,disabled=false,autoFocus=false}:Props){
 const [inputValue,setInputValue]=useState(initialValue);const [options,setOptions]=useState<VehicleQuickSearchResult[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState(false);const requestId=useRef(0);
 const query=inputValue.normalize('NFKC').trim().replace(/\s+/g,' ');
 useEffect(()=>{if(query.length<2)return;const controller=new AbortController();const current=++requestId.current;const timer=setTimeout(()=>{setLoading(true);setError(false);vehicleCatalogQuickSearch(query,15,controller.signal).then(r=>{if(current===requestId.current)setOptions(r.data)}).catch(e=>{if(e?.name!=='AbortError'&&current===requestId.current){setOptions([]);setError(true)}}).finally(()=>{if(current===requestId.current)setLoading(false)})},350);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 const active=query.length>=2;
 return <Autocomplete<VehicleQuickSearchResult,false,false,true> freeSolo filterOptions={x=>x} options={active?options:[]} inputValue={inputValue} loading={active&&loading} disabled={disabled} clearOnBlur={false} handleHomeEndKeys noOptionsText={error?'Не удалось выполнить поиск. Попробуйте ещё раз.':'Автомобили не найдены'} getOptionLabel={o=>typeof o==='string'?o:`${o.manufacturerName} ${o.modelName}`} isOptionEqualToValue={(a,b)=>typeof b!=='string'&&a.modelId===b.modelId&&a.specificationId===b.specificationId} onInputChange={(_,v,reason)=>{if(reason!=='reset')setInputValue(v)}} onChange={(_,v)=>{if(v&&typeof v!=='string')onSelect(v)}} sx={{mt:1.5,width:'100%'}} slotProps={{paper:{sx:{maxWidth:'calc(100vw - 32px)'}}}} renderOption={(props,o)=><Box component='li' {...props} sx={{minHeight:56,alignItems:'flex-start!important'}}><Box><Typography sx={{fontWeight:700}}>{o.manufacturerName} {o.modelName}</Typography><Typography variant='body2' color='text.secondary'>{details(o)}</Typography></Box></Box>} renderInput={params=><Box sx={{position:'relative'}}><SearchRounded sx={{position:'absolute',left:14,top:17,zIndex:1,color:'text.secondary'}}/><TextField {...params} autoFocus={autoFocus} placeholder='Введите марку или модель...' error={active&&error} helperText={active&&error?'Не удалось выполнить поиск. Попробуйте ещё раз.':query.length===1?'Введите ещё один символ':undefined} sx={{'& input':{pl:'44px!important'}}}/></Box>}/>;
}
