'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useState } from 'react';
import { ProtectedLayout } from '../../../components/protected-layout';
import { activateWarehouse,createWarehouse,deactivateWarehouse,deleteWarehouse,getWarehouses,setDefaultWarehouse,ShopWarehouse,updateWarehouse } from '../../../lib/api';
export default function WarehousesPage(){
 const[rows,setRows]=useState<ShopWarehouse[]>([]);const[editing,setEditing]=useState<ShopWarehouse|null>(null);const[form,setForm]=useState({name:'',code:'',address:'',note:''});const[error,setError]=useState('');
 const load=()=>getWarehouses().then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();setError('');try{if(editing)await updateWarehouse(editing.id,form);else await createWarehouse(form);setEditing(null);setForm({name:'',code:'',address:'',note:''});await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 async function action(work:()=>Promise<unknown>){setError('');try{await work();await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 return <ProtectedLayout><div className="space-y-5"><h1 className="text-2xl font-bold">Склады</h1>{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
 <form onSubmit={save} className="grid gap-3 rounded-xl bg-white p-5 ring-1 ring-slate-200 md:grid-cols-4"><input required maxLength={120} placeholder="Название*" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded border p-2"/><input maxLength={40} placeholder="Код" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="rounded border p-2"/><input placeholder="Адрес" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="rounded border p-2"/><input placeholder="Примечание" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className="rounded border p-2"/><button className="rounded bg-blue-600 px-4 py-2 text-white">{editing?'Сохранить':'Создать склад'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm({name:'',code:'',address:'',note:''})}} className="rounded border px-4">Отмена</button>}</form>
 <div className="overflow-x-auto rounded-xl bg-white ring-1 ring-slate-200"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-3">Название</th><th>Код</th><th>Адрес</th><th>Остатков</th><th>Единиц</th><th>По умолчанию</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-3 font-medium">{row.name}</td><td>{row.code||'—'}</td><td>{row.address||'—'}</td><td>{row._count.inventoryItems}</td><td>{row.totalQuantity}</td><td>{row.isDefault?'Да':'—'}</td><td>{row.isActive?'Активен':'Отключён'}</td><td className="space-x-2 py-2"><Link href={`/inventory?warehouseId=${row.id}`} className="text-blue-700">Остатки</Link><button onClick={()=>{setEditing(row);setForm({name:row.name,code:row.code??'',address:row.address??'',note:row.note??''})}}>Изменить</button>{!row.isDefault&&<button onClick={()=>void action(()=>setDefaultWarehouse(row.id))}>Основной</button>}{row.isActive&&!row.isDefault?<button onClick={()=>window.confirm('Деактивировать склад?')&&void action(()=>deactivateWarehouse(row.id))}>Отключить</button>:!row.isActive?<button onClick={()=>void action(()=>activateWarehouse(row.id))}>Включить</button>:null}{row._count.inventoryItems===0&&!row.isDefault&&<button className="text-red-700" onClick={()=>window.confirm('Удалить пустой склад?')&&void action(()=>deleteWarehouse(row.id))}>Удалить</button>}</td></tr>)}</tbody></table></div>
 </div></ProtectedLayout>
}
