'use client';
import { useEffect,useState } from 'react';
import { ProtectedLayout } from '../../../../components/protected-layout';
import { cancelInventoryTransfer,completeInventoryTransfer,createInventoryTransfer,getInventoryTransfers,getWarehouses,inventoryList,InventoryItem,InventoryTransfer,ShopWarehouse } from '../../../../lib/api';
export default function TransfersPage(){
 const[warehouses,setWarehouses]=useState<ShopWarehouse[]>([]);const[transfers,setTransfers]=useState<InventoryTransfer[]>([]);const[items,setItems]=useState<InventoryItem[]>([]);const[from,setFrom]=useState('');const[to,setTo]=useState('');const[selected,setSelected]=useState<Record<string,number>>({});const[error,setError]=useState('');
 const load=()=>Promise.all([getWarehouses(),getInventoryTransfers()]).then(([w,t])=>{setWarehouses(w.filter(x=>x.isActive));setTransfers(t)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!from)return;inventoryList({warehouseId:from,inStock:true,limit:100}).then(r=>setItems(r.data))},[from]);
 async function create(){const lines=Object.entries(selected).filter(([,q])=>q>0).map(([sourceInventoryItemId,quantity])=>({sourceInventoryItemId,quantity}));try{await createInventoryTransfer({fromWarehouseId:from,toWarehouseId:to,items:lines});setSelected({});await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 async function action(work:()=>Promise<unknown>){try{await work();await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 return <ProtectedLayout><div className="space-y-5"><h1 className="text-2xl font-bold">Перемещения между складами</h1>{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
 <section className="rounded-xl bg-white p-5 ring-1 ring-slate-200"><div className="flex gap-3"><select value={from} onChange={e=>setFrom(e.target.value)} className="rounded border p-2"><option value="">Исходный склад</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)} className="rounded border p-2"><option value="">Принимающий склад</option>{warehouses.filter(w=>w.id!==from).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div>
 <table className="mt-4 w-full text-sm"><thead><tr className="text-left"><th>Позиция</th><th>Артикул/OEM</th><th>Доступно</th><th>Переместить</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="py-2">{item.partCatalogItem.name}</td><td>{item.sku||item.oemNumber||'—'}</td><td>{item.quantity}</td><td><input type="number" min="0" max={item.quantity} value={selected[item.id]??0} onChange={e=>setSelected({...selected,[item.id]:Number(e.target.value)})} className="w-24 rounded border p-1"/></td></tr>)}</tbody></table><button disabled={!from||!to||!Object.values(selected).some(q=>q>0)} onClick={()=>void create()} className="mt-4 rounded bg-blue-600 px-4 py-2 text-white disabled:opacity-40">Сохранить черновик</button></section>
 <section className="rounded-xl bg-white p-5 ring-1 ring-slate-200"><h2 className="font-semibold">История</h2><table className="mt-3 w-full text-sm"><thead><tr className="text-left"><th>Номер</th><th>Откуда</th><th>Куда</th><th>Позиций</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{transfers.map(t=><tr key={t.id} className="border-t"><td className="py-2">{t.number}</td><td>{t.fromWarehouse.name}</td><td>{t.toWarehouse.name}</td><td>{t.items.length}</td><td>{t.status}</td><td>{t.status==='DRAFT'&&<span className="space-x-2"><button onClick={()=>window.confirm('Завершить перемещение?')&&void action(()=>completeInventoryTransfer(t.id))} className="text-emerald-700">Завершить</button><button onClick={()=>window.confirm('Отменить черновик?')&&void action(()=>cancelInventoryTransfer(t.id))} className="text-red-700">Отменить</button></span>}</td></tr>)}</tbody></table></section>
 </div></ProtectedLayout>
}
