'use client';
import { use, useCallback, useEffect, useState } from 'react';
import { ProtectedLayout } from '../../../../components/protected-layout';
import { cancelCustomerOrder, completeCustomerOrder, confirmCustomerOrder, createOrderPayment, CustomerOrder, extendCustomerOrder, getCustomerOrder, getOrderFinance, OrderFinance, PaymentMethod, readyCustomerOrder, refundOrderPayment, reserveCustomerOrder } from '../../../../lib/api';
export default function OrderPage({params}:{params:Promise<{id:string}>}){
 const{id}=use(params);const[data,setData]=useState<CustomerOrder|null>(null);const[finance,setFinance]=useState<OrderFinance|null>(null);const[error,setError]=useState('');
 const load=useCallback(async()=>{try{setData(await getCustomerOrder(id));setFinance(await getOrderFinance(id))}catch(e){setError(e instanceof Error?e.message:'Ошибка')}},[id]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function action(work:()=>Promise<unknown>){try{setError('');await work();await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 async function receivePayment(){const amount=Number(prompt('Сумма оплаты'));if(!amount)return;const method=(prompt('Способ: CASH, CARD, BANK_TRANSFER, MOBILE_WALLET, OTHER','CASH')||'CASH') as PaymentMethod;await action(()=>createOrderPayment(id,{amount,method}));}
 async function refund(){const amount=Number(prompt('Сумма возврата'));const reason=prompt('Причина возврата');if(amount&&reason)await action(()=>refundOrderPayment(id,{amount,reason}));}
 if(!data)return <ProtectedLayout><p>{error||'Загрузка...'}</p></ProtectedLayout>;
 const groups=Object.entries(data.items.reduce<Record<string,typeof data.items>>((result,item)=>({...result,[item.shopName]:[...(result[item.shopName]??[]),item]}),{}));
 return <ProtectedLayout><div className="space-y-5"><header><h1 className="text-3xl font-bold">{data.number}</h1><p>{data.customerNameSnapshot} · {data.customerPhoneSnapshot||'без телефона'} · {data.status}</p></header>{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
 <section className="rounded-xl bg-white p-5"><p>Резерв до: {data.reservationExpiresAt?new Date(data.reservationExpiresAt).toLocaleString():'—'}</p><p>Получение: {data.deliveryType} {data.deliveryAddress}</p></section>
 {groups.map(([shop,items])=><section key={shop} className="rounded-xl bg-white p-5"><h2 className="font-bold">{shop}</h2>{items.map(x=><div className="flex justify-between border-t py-2" key={x.id}><span>{x.catalogItemName} · {x.warehouseName}</span><span>{x.quantity} × {x.unitPrice} = {x.total}</span></div>)}</section>)}
 <section className="rounded-xl bg-white p-5"><h2 className="text-xl font-bold">Финансы</h2>{finance?<><div className="mt-3 grid gap-3 md:grid-cols-4"><Metric label="Итого заказа" value={finance.order.total}/><Metric label="Оплачено" value={finance.order.paidAmount}/><Metric label="Долг клиента" value={finance.order.dueAmount}/><Metric label="Доход платформы" value={finance.platform.totalRevenue}/><Metric label="К выплате магазинам" value={String(finance.shops.reduce((s,x)=>s+Number(x.payableAmount),0))}/><Metric label="Выплачено магазинам" value={String(finance.shops.reduce((s,x)=>s+Number(x.paidToShop),0))}/><Metric label="Долг магазинам" value={String(finance.shops.reduce((s,x)=>s+Number(x.outstandingToShop),0))}/></div><div className="mt-4 flex gap-2"><button className="rounded bg-emerald-600 px-4 py-2 text-white" onClick={()=>void receivePayment()}>Принять оплату</button><button className="rounded border px-4 py-2" onClick={()=>void refund()}>Оформить возврат</button></div>{finance.payments.map(p=><p className="mt-2 text-sm" key={p.id}>{new Date(p.receivedAt).toLocaleString()} · {p.method} · {p.amount} · {p.status}</p>)}</>:<p>Финансы доступны SUPER_ADMIN</p>}</section>
 <div className="flex gap-2">{data.status==='DRAFT'&&<button className="rounded bg-blue-600 px-4 py-2 text-white" onClick={()=>action(()=>reserveCustomerOrder(id))}>Резервировать</button>}{data.status==='RESERVED'&&<><button className="rounded bg-emerald-600 px-4 py-2 text-white" onClick={()=>action(()=>confirmCustomerOrder(id))}>Подтвердить и продать</button><button className="rounded border px-4" onClick={()=>action(()=>extendCustomerOrder(id,120))}>Продлить на 2 часа</button></>}{data.status==='CONFIRMED'&&<button className="rounded bg-blue-600 px-4 py-2 text-white" onClick={()=>action(()=>readyCustomerOrder(id))}>Готов к выдаче</button>}{data.status==='READY'&&<button className="rounded bg-emerald-600 px-4 py-2 text-white" onClick={()=>action(()=>completeCustomerOrder(id))}>Завершить</button>}{['DRAFT','RESERVED'].includes(data.status)&&<button className="rounded border border-red-300 px-4 text-red-700" onClick={()=>{const reason=prompt('Причина отмены');if(reason)void action(()=>cancelCustomerOrder(id,reason))}}>Отменить</button>}</div>
 {data.sales.length>0&&<section><h2 className="font-bold">Связанные продажи</h2>{data.sales.map(s=><p key={s.id}>{s.number} · {s.shop.name} · {s.totalAmount} · {s.status}</p>)}</section>}<section><h2 className="font-bold">История статусов</h2>{data.statusHistory.map(h=><p key={h.id}>{new Date(h.createdAt).toLocaleString()} — {h.status} {h.note}</p>)}</section></div></ProtectedLayout>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded border p-3"><small className="text-slate-500">{label}</small><b className="block text-xl">{value} TJS</b></div>}
