'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { ProtectedLayout } from '../../../components/protected-layout';
import { cancelPurchase, getPurchaseById, PurchaseDetails } from '../../../lib/api';

const date = (value: string) => new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export default function PurchaseDetailsPage() {
  const params = useParams<{ id: string }>(); const [purchase, setPurchase] = useState<PurchaseDetails | null>(null); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setPurchase(await getPurchaseById(params.id)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Не удалось загрузить закупку'); } finally { setLoading(false); } }, [params.id]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function cancel() { if (!purchase || !reason.trim()) { setError('Укажите причину отмены'); return; } if (!window.confirm(`Отменить закупку ${purchase.number}? Остаток будет уменьшен.`)) return; setBusy(true); setError(''); try { await cancelPurchase(purchase.id, reason.trim()); setNotice('Закупка отменена. Остатки уменьшены.'); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Не удалось отменить закупку'); } finally { setBusy(false); } }
  return <ProtectedLayout><Link href="/purchases" className="text-sm text-blue-700">← Все закупки</Link>{loading ? <p className="mt-5 text-slate-500">Загрузка…</p> : error && !purchase ? <p className="mt-5 rounded bg-red-50 p-3 text-red-700">{error}</p> : purchase && <><div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{purchase.number}</h1><p className="text-slate-500">{date(purchase.purchasedAt)} · {purchase.shop.name}</p></div><span className={purchase.status === 'COMPLETED' ? 'rounded bg-emerald-50 px-3 py-1 text-emerald-700' : 'rounded bg-slate-100 px-3 py-1 text-slate-600'}>{purchase.status === 'COMPLETED' ? 'Проведена' : 'Отменена'}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="Итог" value={`${purchase.totalAmount} ${purchase.currency}`}/><Info label="Поставщик" value={purchase.supplierName ?? 'Не указан'}/><Info label="Телефон" value={purchase.supplierPhone ?? 'Не указан'}/></div>{purchase.invoiceNumber && <p className="mt-3 text-sm text-slate-500">Накладная: {purchase.invoiceNumber}</p>}{purchase.notes && <p className="mt-4 rounded bg-white p-3 text-slate-600">{purchase.notes}</p>}<div className="mt-5 overflow-x-auto rounded-xl bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Товар</th><th>Код / OEM</th><th>Количество</th><th>Закупочная цена</th><th>Сумма</th></tr></thead><tbody>{purchase.items.map((item) => <tr key={item.id} className="border-b"><td className="p-3"><b>{item.itemName}</b><br/><span className="text-slate-500">{item.partCatalogItem.category.name}</span></td><td>{item.partCatalogItem.internalCode}<br/>{item.oemNumber ?? item.inventoryItem.oemNumber ?? '—'}</td><td>{item.quantity}</td><td>{item.purchasePrice} {purchase.currency}</td><td>{item.lineTotal} {purchase.currency}</td></tr>)}</tbody></table></div>{purchase.status === 'COMPLETED' && <section className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-semibold">Отмена закупки</h2><p className="mt-1 text-sm text-slate-600">Операция будет отклонена, если товара уже недостаточно на складе.</p><input value={reason} onChange={(event) => setReason(event.target.value)} className="mt-3 w-full rounded border p-2" placeholder="Причина отмены"/><button disabled={busy} onClick={() => void cancel()} className="mt-3 rounded bg-red-600 px-4 py-2 text-white disabled:bg-slate-300">{busy ? 'Отмена…' : 'Отменить закупку'}</button></section>}{notice && <p className="mt-4 rounded bg-emerald-50 p-3 text-emerald-700">{notice}</p>}{error && purchase && <p className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{purchase.status === 'CANCELLED' && <p className="mt-4 rounded bg-slate-100 p-3 text-slate-600">Причина отмены: {purchase.cancelReason ?? 'не указана'}</p>}</>}</ProtectedLayout>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded bg-white p-3"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
