'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ProtectedLayout } from '../../../../components/protected-layout';
import { createCustomerOrder, OrderInventorySearchItem, reserveCustomerOrder, searchOrderInventory } from '../../../../lib/api';

export default function NewOrderPage(){const router=useRouter();const[name,setName]=useState('');const[phone,setPhone]=useState('');const[q,setQ]=useState('');const[found,setFound]=useState<OrderInventorySearchItem[]>([]);const[selected,setSelected]=useState<Array<OrderInventorySearchItem&{requested:number;price:number}>>([]);const[deliveryType,setDeliveryType]=useState<'PICKUP'|'DELIVERY'>('PICKUP');const[address,setAddress]=useState('');const[error,setError]=useState('');
async function submit(reserve:boolean){try{const order=await createCustomerOrder({customer:{fullName:name,phone},deliveryType,deliveryAddress:address||undefined,items:selected.map(x=>({inventoryItemId:x.inventoryItemId,quantity:x.requested,unitPrice:x.price}))});if(reserve)await reserveCustomerOrder(order.id);router.push(`/admin/orders/${order.id}`)}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
return <ProtectedLayout><div className="space-y-5"><h1 className="text-3xl font-bold">Новый заказ</h1>{error&&<p className="text-red-700">{error}</p>}<section className="rounded-xl bg-white p-5"><h2 className="font-bold">1. Клиент</h2><div className="mt-3 flex gap-3"><input className="rounded border p-2" placeholder="Имя" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded border p-2" placeholder="Телефон" value={phone} onChange={e=>setPhone(e.target.value)}/></div></section>
<section className="rounded-xl bg-white p-5"><h2 className="font-bold">2. Подбор товаров</h2><div className="my-3 flex gap-2"><input className="flex-1 rounded border p-2" value={q} onChange={e=>setQ(e.target.value)} placeholder="Название, артикул, OEM"/><button className="rounded bg-slate-800 px-4 text-white" onClick={async()=>setFound((await searchOrderInventory({query:q,limit:50})).data)}>Найти</button></div>{found.map(x=><div key={x.inventoryItemId} className="flex items-center justify-between border-t py-2"><span>{x.catalogItemName} · {x.shopName} / {x.warehouseName} · физически {x.quantity}, резерв {x.reservedQuantity}, доступно {x.availableQuantity} · {x.salePrice}</span><button className="text-blue-700" onClick={()=>!selected.some(s=>s.inventoryItemId===x.inventoryItemId)&&setSelected([...selected,{...x,requested:1,price:Number(x.salePrice)}])}>Добавить</button></div>)}</section>
<section className="rounded-xl bg-white p-5"><h2 className="font-bold">3. Цена и количество</h2>{selected.map((x,index)=><div className="flex gap-3 border-t py-2" key={x.inventoryItemId}><span className="flex-1">{x.catalogItemName} — {x.shopName}</span><input className="w-20 rounded border p-1" type="number" min={1} max={x.availableQuantity} value={x.requested} onChange={e=>setSelected(selected.map((s,i)=>i===index?{...s,requested:Number(e.target.value)}:s))}/><input className="w-28 rounded border p-1" type="number" min={0} value={x.price} onChange={e=>setSelected(selected.map((s,i)=>i===index?{...s,price:Number(e.target.value)}:s))}/></div>)}</section>
<section className="rounded-xl bg-white p-5"><h2 className="font-bold">4. Получение и проверка</h2><select className="my-3 rounded border p-2" value={deliveryType} onChange={e=>setDeliveryType(e.target.value as 'PICKUP'|'DELIVERY')}><option value="PICKUP">Самовывоз</option><option value="DELIVERY">Доставка</option></select>{deliveryType==='DELIVERY'&&<input className="ml-3 rounded border p-2" placeholder="Адрес" value={address} onChange={e=>setAddress(e.target.value)}/>}<p>Итого: {selected.reduce((sum,x)=>sum+x.requested*x.price,0).toFixed(2)} TJS</p><div className="mt-4 flex gap-3"><button className="rounded border px-4 py-2" disabled={!name||!selected.length} onClick={()=>void submit(false)}>Сохранить черновик</button><button className="rounded bg-blue-600 px-4 py-2 text-white" disabled={!name||!selected.length} onClick={()=>void submit(true)}>Создать и зарезервировать</button></div></section></div></ProtectedLayout>}
