'use client';
import { useEffect,useMemo,useState } from 'react';
import { ProtectedLayout } from '../../../../components/protected-layout';
import { cancelStocktake,completeStocktake,createStocktake,getStocktakes,getWarehouses,ShopWarehouse,Stocktake,updateStocktakeItems } from '../../../../lib/api';
export default function StocktakesPage(){
 const[warehouses,setWarehouses]=useState<ShopWarehouse[]>([]);const[rows,setRows]=useState<Stocktake[]>([]);const[selected,setSelected]=useState<Stocktake|null>(null);const[warehouseId,setWarehouseId]=useState('');const[actual,setActual]=useState<Record<string,number>>({});const[onlyDifferences,setOnlyDifferences]=useState(false);const[error,setError]=useState('');
 const load=()=>Promise.all([getWarehouses(),getStocktakes()]).then(([w,s])=>{setWarehouses(w.filter(x=>x.isActive));setRows(s)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
 const shown=useMemo(()=>selected?.items.filter(item=>!onlyDifferences||(actual[item.inventoryItemId]??item.actualQuantity??item.expectedQuantity)!==item.expectedQuantity)??[],[selected,actual,onlyDifferences]);
 function open(stocktake:Stocktake){setSelected(stocktake);setActual(Object.fromEntries(stocktake.items.map(item=>[item.inventoryItemId,item.actualQuantity??item.expectedQuantity])))}
 async function create(){try{const result=await createStocktake({warehouseId});open(result);await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 async function save(){if(!selected)return;try{const result=await updateStocktakeItems(selected.id,selected.items.map(item=>({inventoryItemId:item.inventoryItemId,actualQuantity:actual[item.inventoryItemId]??item.expectedQuantity})));open(result);await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 async function action(work:()=>Promise<Stocktake>){try{const result=await work();open(result);await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 const stats=selected?selected.items.reduce((s,item)=>{const diff=(actual[item.inventoryItemId]??item.actualQuantity??item.expectedQuantity)-item.expectedQuantity;s.matched+=diff===0?1:0;s.surplus+=diff>0?1:0;s.shortage+=diff<0?1:0;s.total+=diff;return s},{matched:0,surplus:0,shortage:0,total:0}):null;
 return <ProtectedLayout><div className="space-y-5"><h1 className="text-2xl font-bold">Инвентаризация</h1>{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<section className="rounded-xl bg-white p-5 ring-1 ring-slate-200"><select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className="rounded border p-2"><option value="">Выберите склад</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><button disabled={!warehouseId} onClick={()=>void create()} className="ml-3 rounded bg-blue-600 px-4 py-2 text-white disabled:opacity-40">Создать инвентаризацию</button><div className="mt-4 flex flex-wrap gap-2">{rows.map(row=><button key={row.id} onClick={()=>open(row)} className="rounded border px-3 py-2">{row.number} · {row.warehouse.name} · {row.status}</button>)}</div></section>
 {selected&&<section className="rounded-xl bg-white p-5 ring-1 ring-slate-200"><div className="flex justify-between"><h2 className="font-semibold">{selected.number} — {selected.warehouse.name}</h2><label><input type="checkbox" checked={onlyDifferences} onChange={e=>setOnlyDifferences(e.target.checked)}/> Только расхождения</label></div>{stats&&<div className="my-3 flex gap-3 text-sm"><span>Совпало: {stats.matched}</span><span>Излишек: {stats.surplus}</span><span>Недостача: {stats.shortage}</span><span>Общая разница: {stats.total}</span></div>}<table className="w-full text-sm"><thead><tr className="text-left"><th>Позиция</th><th>Ожидалось</th><th>Фактически</th><th>Разница</th></tr></thead><tbody>{shown.map(item=>{const value=actual[item.inventoryItemId]??item.expectedQuantity;return <tr key={item.id} className="border-t"><td className="py-2">{item.inventoryItem.partCatalogItem.name}</td><td>{item.expectedQuantity}</td><td><input disabled={selected.status!=='DRAFT'} type="number" min="0" value={value} onChange={e=>setActual({...actual,[item.inventoryItemId]:Number(e.target.value)})} className="w-24 rounded border p-1"/></td><td>{value-item.expectedQuantity}</td></tr>})}</tbody></table>{selected.status==='DRAFT'&&<div className="mt-4 space-x-2"><button onClick={()=>void save()} className="rounded border px-4 py-2">Сохранить</button><button onClick={()=>window.confirm('Завершить инвентаризацию? Остатки будут скорректированы.')&&void action(()=>completeStocktake(selected.id))} className="rounded bg-emerald-600 px-4 py-2 text-white">Завершить</button><button onClick={()=>window.confirm('Отменить черновик?')&&void action(()=>cancelStocktake(selected.id))} className="rounded bg-red-50 px-4 py-2 text-red-700">Отменить</button></div>}</section>}</div></ProtectedLayout>
}
